# A bounding box containing the entire city
bounds:
  n: 53.9458558
  e: -1.2903452
  s: 53.6983747
  w: -1.8003617
# Features that can be found in CKAN sources
ckan:
  'http://leedsdatamill.org/api/1/':
    nns:
      package: 'neighbourhood-network-schemes'
      columns:
        name: nameOfNeighbourhoodNetworkScheme
        easting: Easting
        northing: Northing
    changing_place:
      package: 'changing-places-toilets-in-leeds'
      columns:
        name: Location
        easting: EASTING
        northing: NORTHING
