# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d8b94bc45d4cf90f52be719aa49743e5747fa64b726ffdca8a26d6e57599b312f946cdb69207977f3b07baf4cd4fbd381429ab6f494d064f426b6b909626731

test:
  secret_key_base: ea003009e0d458e5acbe2be32de6c1a94d8f2b6e1803f3efa6a79ceb12e9d56185e4a0b61edff7a3a4aa4e3be9f1112ceea3e105b42a953a843e941254324b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
